imports:
    - { resource: parameters.ini }

app.config:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine.dbal:
    driver:   %database_driver%
    host:     %database_host%
    dbname:   %database_name%
    user:     %database_user%
    password: %database_password%
    logging:  %kernel.debug%

doctrine.orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        Blog: { prefix: Sensio\Blog, type: annotation, dir: %kernel.root_dir%/../src/Sensio/Blog }

# Swiftmailer Configuration
swiftmailer.config:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%

